apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deploy
    spec:
      containers:
      - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        name: flaskex
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.memRequest }}
            cpu: {{ .Values.resources.cpuRequest }}